name: mbhvip
version: '1.0-SNAPSHOT'
main: org.best.mbhvip.Mbhvip
api-version: '1.19'
commands:
  ipwhitelist:
    description: Whitelist a player with an IP address
    usage: /ipwhitelist <username> <ip>
    permission: operators